version: "2"

services:
  mysql:
    image: mysql
    container_name: tools-mysql
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - ./env/mysql.env
    ports:
      - "3306:3306"